Update aws-resource-dms-replicationtask.md
Replicate in CFN template:
1) when define 'CdcStartTime': "2022-01-07T12:02:59"  
>>> Error: Property validation failure: [Value of property {/CdcStartTime} does not match type {Number}]

2) when define 'CdcStartTime': 1641556979
>>> From AWS DMS console: Change data capture (CDC) start position: 1970-01-19T23:59:16

3) when define 'CdcStartTime': 1641556979000
>>> From AWS DMS console: Change data capture (CDC) start position: 2022-01-07T12:02:59

Seems in CFN pre-check, CdcStartTime need to be a 'Type: Number', and the Number need to be in epoch timestamp in milliseconds format.

Also, inside API reference, CreateReplicationTask API:
In Request Syntax >>> CdcStartTime Type: number
----------------------
{   ...
    "CdcStartTime": number 
    ...
}
----------------------