Update aws-properties-codepipeline-pipeline-artifactstore-encryptionkey.md
When you use the KMS Key ID, you will have failures with CodeBuild when it tries to upload the artifact back to the artifact store.  It will look for the key in its own account and will not find the key and result in:
CLIENT_ERROR: Error in UPLOAD_ARTIFACTS phase: KMS.NotFoundException: Key 'arn:aws:kms:us-east-1:<obscured>:key/<obscured>' does not exist status code: 400, request id: <obscured>, host id: <obscured>